### ISSUE TITLE
Figure out a good color scheme

### ISSUE THREAD

**Issue by basilysf1709** [Muslims-in-Tech-MIT/muslims-in-tech-landing#6]
- [ ] Use https://coolors.co/ to get a good primary, secondary and tertiary colour scheme for the website

**Comment by basilysf1709** [comment]
@faizm10 Look at the tailwind.config.ts and try to figure out a color scheme! Lmk if you need any help with this.

**Comment by faizm10** [comment]
> @faizm10 Look at the tailwind.config.ts and try to figure out a color scheme! Lmk if you need any help with this.

@basilysf1709 Talha already did. Did you check the updated tailwind.config.ts? We got primary(brand), secondary colour and tertiary colors...

**Comment by basilysf1709** [comment]
Yeah you can close this

**Comment by basilysf1709** [comment]
@faizm10 close
